on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      # Fetch app token
      - uses: tibdex/github-app-token@v1.5.2
        id: gh-api-token
        with:
          app_id: ${{ secrets.GH_APP_STRIPE_OPENAPI_APP_ID }}
          private_key: ${{ secrets.GH_APP_STRIPE_OPENAPI_PRIVATE_KEY }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.183.0 # Latest version as of 2021-10-28
          args: release -f goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ steps.gh-api-token.outputs.token }}
